### PR TITLE
Add V4L Input Plugin

### PR DESCRIPTION
**Pull request by jnschulze**
Hey folks,
here's my announced V4L2 plugin. However, there's still some work left to do:
- Implement toPropertyMap()/fromPropertyMap()
- Error handling
- elimination of probably slow YUV -> RGB texture conversion

Niklas

### CODE REVIEW

**Comment by brocro** [comment]
Awesome : ) Can't wait to give it a try!

**Comment by brocro** [comment]
Just Adding Niklas' Usage suggestion he sent us : 

For testing, I'd recommend creating a V4L Loopback Device (using https://github.com/umlaeute/v4l2loopback). Just use ffmpeg to pipe some data in: "ffmpeg -re -stream_loop -1 -i test.mp4 -vcodec rawvideo -pix_fmt yuv420p -f v4l2 /dev/video0"

**Comment by xseignard** [comment]
Hello,
I just tried it and it seems to work for me too.
I'm running ubuntu 16.04, and I have no problems.

It is a bit laggy, but I think it is related to my machine, I still need to setup the computer dedicated to the show and try it with 4 videoprojectors.

But so far so good.

Thanks!

**Comment by Looo911** [comment]
Thanks for your work! But unfortunately I can`t get it work. Everytime I try to compile it, I get the following error:

Make Error at /home/cogvis/Desktop/omnidome_v4l2/omnicalib/build.cmake:1 (omni_set_version_for_project):
  Unknown CMake command "omni_set_version_for_project".

Do you guys have any idea, how to handle this?

**Comment by nischu7** [comment]
It looks like there's some CMake macro naming inconsistency between omnicalib and cm8kr. The issue is caused by the latest commit of omnicalib (see WilstonOreo/omnicalib@5dcea24eb68fab19860e37c272f32288cd3fce71). As a quick fix, just revert to the previous omnicalib commit: WilstonOreo/omnicalib@58b9b552b91589e073518126c58b13f78512183b.

**Comment by yavuzcakir16** [comment]
Is there anyone put this plug in on omnidome ? Do you have any tutorial ?

**Pull request closed without merging**
